/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.Mekanik;

//--- Services 
import org.demo.business.service.MekanikService;


/**
 * Spring MVC controller for 'Mekanik' management.
 */
@Controller
@RequestMapping("/mekanik")
public class MekanikController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "mekanik";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "mekanik/form";
	private static final String JSP_LIST   = "mekanik/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/mekanik/create";
	private static final String SAVE_ACTION_UPDATE   = "/mekanik/update";

	//--- Main entity service
	@Resource
    private MekanikService mekanikService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MekanikController() {
		super(MekanikController.class, MAIN_ENTITY_NAME );
		log("MekanikController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param mekanik
	 */
	private void populateModel(Model model, Mekanik mekanik, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, mekanik);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Mekanik found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Mekanik> list = mekanikService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Mekanik
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Mekanik mekanik = new Mekanik();	
		populateModel( model, mekanik, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Mekanik
	 * @param model Spring MVC model
	 * @param idMekanik  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idMekanik}")
	public String formForUpdate(Model model, @PathVariable("idMekanik") String idMekanik ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Mekanik mekanik = mekanikService.findById(idMekanik);
		populateModel( model, mekanik, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param mekanik  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Mekanik mekanik, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Mekanik mekanikCreated = mekanikService.create(mekanik); 
				model.addAttribute(MAIN_ENTITY_NAME, mekanikCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, mekanik.getIdMekanik() );
			} else {
				populateModel( model, mekanik, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "mekanik.error.create", e);
			populateModel( model, mekanik, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param mekanik  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Mekanik mekanik, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Mekanik mekanikSaved = mekanikService.update(mekanik);
				model.addAttribute(MAIN_ENTITY_NAME, mekanikSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, mekanik.getIdMekanik());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, mekanik, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "mekanik.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, mekanik, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idMekanik  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idMekanik}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idMekanik") String idMekanik) {
		log("Action 'delete'" );
		try {
			mekanikService.delete( idMekanik );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "mekanik.error.delete", e);
		}
		return redirectToList();
	}

	@RequestMapping(value = "/pdf", method = RequestMethod.GET)
	public String getPdfReport(Model model, HttpServletResponse response) {
		List<Mekanik> entities = (List<Mekanik>) mekanikService.findAll();
		JRDataSource dataSource = new JRBeanCollectionDataSource(entities);
		model.addAttribute("dataSource", dataSource);
		return "pdfReport";
	}

	@RequestMapping(value = "/xls", method = RequestMethod.GET)
	public String getXlsReport(Model model, HttpServletResponse response) {
		List<Mekanik> entities = (List<Mekanik>) mekanikService.findAll();
		JRDataSource dataSource = new JRBeanCollectionDataSource(entities);
		model.addAttribute("dataSource", dataSource);
		return "xlsReport";
	}

}
