/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.PembelianDetail;
import org.demo.bean.PembelianHeader;

//--- Services 
import org.demo.business.service.PembelianDetailService;
import org.demo.business.service.PembelianHeaderService;

//--- List Items 
import org.demo.web.listitem.PembelianHeaderListItem;

/**
 * Spring MVC controller for 'PembelianDetail' management.
 */
@Controller
@RequestMapping("/pembelianDetail")
public class PembelianDetailController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "pembelianDetail";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "pembelianDetail/form";
	private static final String JSP_LIST   = "pembelianDetail/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/pembelianDetail/create";
	private static final String SAVE_ACTION_UPDATE   = "/pembelianDetail/update";

	//--- Main entity service
	@Resource
    private PembelianDetailService pembelianDetailService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private PembelianHeaderService pembelianHeaderService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public PembelianDetailController() {
		super(PembelianDetailController.class, MAIN_ENTITY_NAME );
		log("PembelianDetailController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "PembelianHeader"
	 * @param model
	 */
	private void populateListOfPembelianHeaderItems(Model model) {
		List<PembelianHeader> list = pembelianHeaderService.findAll();
		List<PembelianHeaderListItem> items = new LinkedList<PembelianHeaderListItem>();
		for ( PembelianHeader pembelianHeader : list ) {
			items.add(new PembelianHeaderListItem( pembelianHeader ) );
		}
		model.addAttribute("listOfPembelianHeaderItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param pembelianDetail
	 */
	private void populateModel(Model model, PembelianDetail pembelianDetail, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, pembelianDetail);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfPembelianHeaderItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfPembelianHeaderItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of PembelianDetail found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<PembelianDetail> list = pembelianDetailService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new PembelianDetail
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		PembelianDetail pembelianDetail = new PembelianDetail();	
		populateModel( model, pembelianDetail, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing PembelianDetail
	 * @param model Spring MVC model
	 * @param idPembelianDetail  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idPembelianDetail}")
	public String formForUpdate(Model model, @PathVariable("idPembelianDetail") Integer idPembelianDetail ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		PembelianDetail pembelianDetail = pembelianDetailService.findById(idPembelianDetail);
		populateModel( model, pembelianDetail, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param pembelianDetail  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid PembelianDetail pembelianDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				PembelianDetail pembelianDetailCreated = pembelianDetailService.create(pembelianDetail); 
				model.addAttribute(MAIN_ENTITY_NAME, pembelianDetailCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, pembelianDetail.getIdPembelianDetail() );
			} else {
				populateModel( model, pembelianDetail, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "pembelianDetail.error.create", e);
			populateModel( model, pembelianDetail, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param pembelianDetail  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid PembelianDetail pembelianDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				PembelianDetail pembelianDetailSaved = pembelianDetailService.update(pembelianDetail);
				model.addAttribute(MAIN_ENTITY_NAME, pembelianDetailSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, pembelianDetail.getIdPembelianDetail());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, pembelianDetail, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "pembelianDetail.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, pembelianDetail, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idPembelianDetail  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idPembelianDetail}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idPembelianDetail") Integer idPembelianDetail) {
		log("Action 'delete'" );
		try {
			pembelianDetailService.delete( idPembelianDetail );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "pembelianDetail.error.delete", e);
		}
		return redirectToList();
	}

}
