/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.PenjualanHeader;

//--- Services 
import org.demo.business.service.PenjualanHeaderService;


/**
 * Spring MVC controller for 'PenjualanHeader' management.
 */
@Controller
@RequestMapping("/penjualanHeader")
public class PenjualanHeaderController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "penjualanHeader";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "penjualanHeader/form";
	private static final String JSP_LIST   = "penjualanHeader/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/penjualanHeader/create";
	private static final String SAVE_ACTION_UPDATE   = "/penjualanHeader/update";

	//--- Main entity service
	@Resource
    private PenjualanHeaderService penjualanHeaderService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public PenjualanHeaderController() {
		super(PenjualanHeaderController.class, MAIN_ENTITY_NAME );
		log("PenjualanHeaderController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param penjualanHeader
	 */
	private void populateModel(Model model, PenjualanHeader penjualanHeader, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, penjualanHeader);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of PenjualanHeader found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<PenjualanHeader> list = penjualanHeaderService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new PenjualanHeader
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		PenjualanHeader penjualanHeader = new PenjualanHeader();	
		populateModel( model, penjualanHeader, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing PenjualanHeader
	 * @param model Spring MVC model
	 * @param idPenjualanHeader  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idPenjualanHeader}")
	public String formForUpdate(Model model, @PathVariable("idPenjualanHeader") Integer idPenjualanHeader ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		PenjualanHeader penjualanHeader = penjualanHeaderService.findById(idPenjualanHeader);
		populateModel( model, penjualanHeader, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param penjualanHeader  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid PenjualanHeader penjualanHeader, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				PenjualanHeader penjualanHeaderCreated = penjualanHeaderService.create(penjualanHeader); 
				model.addAttribute(MAIN_ENTITY_NAME, penjualanHeaderCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, penjualanHeader.getIdPenjualanHeader() );
			} else {
				populateModel( model, penjualanHeader, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "penjualanHeader.error.create", e);
			populateModel( model, penjualanHeader, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param penjualanHeader  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid PenjualanHeader penjualanHeader, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				PenjualanHeader penjualanHeaderSaved = penjualanHeaderService.update(penjualanHeader);
				model.addAttribute(MAIN_ENTITY_NAME, penjualanHeaderSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, penjualanHeader.getIdPenjualanHeader());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, penjualanHeader, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "penjualanHeader.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, penjualanHeader, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idPenjualanHeader  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idPenjualanHeader}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idPenjualanHeader") Integer idPenjualanHeader) {
		log("Action 'delete'" );
		try {
			penjualanHeaderService.delete( idPenjualanHeader );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "penjualanHeader.error.delete", e);
		}
		return redirectToList();
	}

}
