/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.PenjualanDetail;
import org.demo.bean.PenjualanHeader;

//--- Services 
import org.demo.business.service.PenjualanDetailService;
import org.demo.business.service.PenjualanHeaderService;

//--- List Items 
import org.demo.web.listitem.PenjualanHeaderListItem;

/**
 * Spring MVC controller for 'PenjualanDetail' management.
 */
@Controller
@RequestMapping("/penjualanDetail")
public class PenjualanDetailController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "penjualanDetail";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "penjualanDetail/form";
	private static final String JSP_LIST   = "penjualanDetail/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/penjualanDetail/create";
	private static final String SAVE_ACTION_UPDATE   = "/penjualanDetail/update";

	//--- Main entity service
	@Resource
    private PenjualanDetailService penjualanDetailService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private PenjualanHeaderService penjualanHeaderService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public PenjualanDetailController() {
		super(PenjualanDetailController.class, MAIN_ENTITY_NAME );
		log("PenjualanDetailController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "PenjualanHeader"
	 * @param model
	 */
	private void populateListOfPenjualanHeaderItems(Model model) {
		List<PenjualanHeader> list = penjualanHeaderService.findAll();
		List<PenjualanHeaderListItem> items = new LinkedList<PenjualanHeaderListItem>();
		for ( PenjualanHeader penjualanHeader : list ) {
			items.add(new PenjualanHeaderListItem( penjualanHeader ) );
		}
		model.addAttribute("listOfPenjualanHeaderItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param penjualanDetail
	 */
	private void populateModel(Model model, PenjualanDetail penjualanDetail, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, penjualanDetail);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfPenjualanHeaderItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfPenjualanHeaderItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of PenjualanDetail found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<PenjualanDetail> list = penjualanDetailService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new PenjualanDetail
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		PenjualanDetail penjualanDetail = new PenjualanDetail();	
		populateModel( model, penjualanDetail, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing PenjualanDetail
	 * @param model Spring MVC model
	 * @param idPenjualanDetail  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idPenjualanDetail}")
	public String formForUpdate(Model model, @PathVariable("idPenjualanDetail") Integer idPenjualanDetail ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		PenjualanDetail penjualanDetail = penjualanDetailService.findById(idPenjualanDetail);
		populateModel( model, penjualanDetail, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param penjualanDetail  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid PenjualanDetail penjualanDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				PenjualanDetail penjualanDetailCreated = penjualanDetailService.create(penjualanDetail); 
				model.addAttribute(MAIN_ENTITY_NAME, penjualanDetailCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, penjualanDetail.getIdPenjualanDetail() );
			} else {
				populateModel( model, penjualanDetail, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "penjualanDetail.error.create", e);
			populateModel( model, penjualanDetail, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param penjualanDetail  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid PenjualanDetail penjualanDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				PenjualanDetail penjualanDetailSaved = penjualanDetailService.update(penjualanDetail);
				model.addAttribute(MAIN_ENTITY_NAME, penjualanDetailSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, penjualanDetail.getIdPenjualanDetail());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, penjualanDetail, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "penjualanDetail.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, penjualanDetail, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idPenjualanDetail  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idPenjualanDetail}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idPenjualanDetail") Integer idPenjualanDetail) {
		log("Action 'delete'" );
		try {
			penjualanDetailService.delete( idPenjualanDetail );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "penjualanDetail.error.delete", e);
		}
		return redirectToList();
	}

}
