/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.ReturPembelian;
import org.demo.bean.PembelianHeader;

//--- Services 
import org.demo.business.service.ReturPembelianService;
import org.demo.business.service.PembelianHeaderService;

//--- List Items 
import org.demo.web.listitem.PembelianHeaderListItem;

/**
 * Spring MVC controller for 'ReturPembelian' management.
 */
@Controller
@RequestMapping("/returPembelian")
public class ReturPembelianController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "returPembelian";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "returPembelian/form";
	private static final String JSP_LIST   = "returPembelian/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/returPembelian/create";
	private static final String SAVE_ACTION_UPDATE   = "/returPembelian/update";

	//--- Main entity service
	@Resource
    private ReturPembelianService returPembelianService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private PembelianHeaderService pembelianHeaderService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ReturPembelianController() {
		super(ReturPembelianController.class, MAIN_ENTITY_NAME );
		log("ReturPembelianController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "PembelianHeader"
	 * @param model
	 */
	private void populateListOfPembelianHeaderItems(Model model) {
		List<PembelianHeader> list = pembelianHeaderService.findAll();
		List<PembelianHeaderListItem> items = new LinkedList<PembelianHeaderListItem>();
		for ( PembelianHeader pembelianHeader : list ) {
			items.add(new PembelianHeaderListItem( pembelianHeader ) );
		}
		model.addAttribute("listOfPembelianHeaderItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param returPembelian
	 */
	private void populateModel(Model model, ReturPembelian returPembelian, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, returPembelian);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfPembelianHeaderItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfPembelianHeaderItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of ReturPembelian found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<ReturPembelian> list = returPembelianService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new ReturPembelian
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		ReturPembelian returPembelian = new ReturPembelian();	
		populateModel( model, returPembelian, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing ReturPembelian
	 * @param model Spring MVC model
	 * @param idreturPembelian  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idreturPembelian}")
	public String formForUpdate(Model model, @PathVariable("idreturPembelian") Integer idreturPembelian ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		ReturPembelian returPembelian = returPembelianService.findById(idreturPembelian);
		populateModel( model, returPembelian, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param returPembelian  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid ReturPembelian returPembelian, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				ReturPembelian returPembelianCreated = returPembelianService.create(returPembelian); 
				model.addAttribute(MAIN_ENTITY_NAME, returPembelianCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, returPembelian.getIdreturPembelian() );
			} else {
				populateModel( model, returPembelian, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "returPembelian.error.create", e);
			populateModel( model, returPembelian, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param returPembelian  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid ReturPembelian returPembelian, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				ReturPembelian returPembelianSaved = returPembelianService.update(returPembelian);
				model.addAttribute(MAIN_ENTITY_NAME, returPembelianSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, returPembelian.getIdreturPembelian());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, returPembelian, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "returPembelian.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, returPembelian, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idreturPembelian  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idreturPembelian}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idreturPembelian") Integer idreturPembelian) {
		log("Action 'delete'" );
		try {
			returPembelianService.delete( idreturPembelian );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "returPembelian.error.delete", e);
		}
		return redirectToList();
	}

}
