/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.ReturPenjualan;
import org.demo.bean.PenjualanHeader;

//--- Services 
import org.demo.business.service.ReturPenjualanService;
import org.demo.business.service.PenjualanHeaderService;

//--- List Items 
import org.demo.web.listitem.PenjualanHeaderListItem;

/**
 * Spring MVC controller for 'ReturPenjualan' management.
 */
@Controller
@RequestMapping("/returPenjualan")
public class ReturPenjualanController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "returPenjualan";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "returPenjualan/form";
	private static final String JSP_LIST   = "returPenjualan/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/returPenjualan/create";
	private static final String SAVE_ACTION_UPDATE   = "/returPenjualan/update";

	//--- Main entity service
	@Resource
    private ReturPenjualanService returPenjualanService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private PenjualanHeaderService penjualanHeaderService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ReturPenjualanController() {
		super(ReturPenjualanController.class, MAIN_ENTITY_NAME );
		log("ReturPenjualanController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "PenjualanHeader"
	 * @param model
	 */
	private void populateListOfPenjualanHeaderItems(Model model) {
		List<PenjualanHeader> list = penjualanHeaderService.findAll();
		List<PenjualanHeaderListItem> items = new LinkedList<PenjualanHeaderListItem>();
		for ( PenjualanHeader penjualanHeader : list ) {
			items.add(new PenjualanHeaderListItem( penjualanHeader ) );
		}
		model.addAttribute("listOfPenjualanHeaderItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param returPenjualan
	 */
	private void populateModel(Model model, ReturPenjualan returPenjualan, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, returPenjualan);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfPenjualanHeaderItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfPenjualanHeaderItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of ReturPenjualan found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<ReturPenjualan> list = returPenjualanService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new ReturPenjualan
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		ReturPenjualan returPenjualan = new ReturPenjualan();	
		populateModel( model, returPenjualan, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing ReturPenjualan
	 * @param model Spring MVC model
	 * @param idreturPenjualan  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idreturPenjualan}")
	public String formForUpdate(Model model, @PathVariable("idreturPenjualan") Integer idreturPenjualan ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		ReturPenjualan returPenjualan = returPenjualanService.findById(idreturPenjualan);
		populateModel( model, returPenjualan, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param returPenjualan  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid ReturPenjualan returPenjualan, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				ReturPenjualan returPenjualanCreated = returPenjualanService.create(returPenjualan); 
				model.addAttribute(MAIN_ENTITY_NAME, returPenjualanCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, returPenjualan.getIdreturPenjualan() );
			} else {
				populateModel( model, returPenjualan, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "returPenjualan.error.create", e);
			populateModel( model, returPenjualan, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param returPenjualan  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid ReturPenjualan returPenjualan, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				ReturPenjualan returPenjualanSaved = returPenjualanService.update(returPenjualan);
				model.addAttribute(MAIN_ENTITY_NAME, returPenjualanSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, returPenjualan.getIdreturPenjualan());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, returPenjualan, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "returPenjualan.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, returPenjualan, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idreturPenjualan  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idreturPenjualan}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idreturPenjualan") Integer idreturPenjualan) {
		log("Action 'delete'" );
		try {
			returPenjualanService.delete( idreturPenjualan );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "returPenjualan.error.delete", e);
		}
		return redirectToList();
	}

}
