/*
 * Created on 25 Jul 2021 ( Time 02:07:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Login;
import org.demo.bean.jpa.LoginEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class LoginServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public LoginServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'LoginEntity' to 'Login'
	 * @param loginEntity
	 */
	public Login mapLoginEntityToLogin(LoginEntity loginEntity) {
		if(loginEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Login login = map(loginEntity, Login.class);

		return login;
	}
	
	/**
	 * Mapping from 'Login' to 'LoginEntity'
	 * @param login
	 * @param loginEntity
	 */
	public void mapLoginToLoginEntity(Login login, LoginEntity loginEntity) {
		if(login == null) {
			return;
		}

		//--- Generic mapping 
		map(login, loginEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}