/*
 * Created on 25 Jul 2021 ( Time 02:07:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.PembelianDetail;
import org.demo.bean.jpa.PembelianDetailEntity;
import org.demo.bean.jpa.PembelianHeaderEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PembelianDetailServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PembelianDetailServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PembelianDetailEntity' to 'PembelianDetail'
	 * @param pembelianDetailEntity
	 */
	public PembelianDetail mapPembelianDetailEntityToPembelianDetail(PembelianDetailEntity pembelianDetailEntity) {
		if(pembelianDetailEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PembelianDetail pembelianDetail = map(pembelianDetailEntity, PembelianDetail.class);

		//--- Link mapping ( link to PembelianHeader )
		if(pembelianDetailEntity.getPembelianHeader2() != null) {
			pembelianDetail.setPembelianHeader(pembelianDetailEntity.getPembelianHeader2().getIdPembelian());
		}
		return pembelianDetail;
	}
	
	/**
	 * Mapping from 'PembelianDetail' to 'PembelianDetailEntity'
	 * @param pembelianDetail
	 * @param pembelianDetailEntity
	 */
	public void mapPembelianDetailToPembelianDetailEntity(PembelianDetail pembelianDetail, PembelianDetailEntity pembelianDetailEntity) {
		if(pembelianDetail == null) {
			return;
		}

		//--- Generic mapping 
		map(pembelianDetail, pembelianDetailEntity);

		//--- Link mapping ( link : pembelianDetail )
		if( hasLinkToPembelianHeader(pembelianDetail) ) {
			PembelianHeaderEntity pembelianHeader1 = new PembelianHeaderEntity();
			pembelianHeader1.setIdPembelian( pembelianDetail.getPembelianHeader() );
			pembelianDetailEntity.setPembelianHeader2( pembelianHeader1 );
		} else {
			pembelianDetailEntity.setPembelianHeader2( null );
		}

	}
	
	/**
	 * Verify that PembelianHeader id is valid.
	 * @param PembelianHeader PembelianHeader
	 * @return boolean
	 */
	private boolean hasLinkToPembelianHeader(PembelianDetail pembelianDetail) {
		if(pembelianDetail.getPembelianHeader() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}