/*
 * Created on 25 Jul 2021 ( Time 02:07:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.PembelianHeader;
import org.demo.bean.jpa.PembelianHeaderEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PembelianHeaderServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PembelianHeaderServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PembelianHeaderEntity' to 'PembelianHeader'
	 * @param pembelianHeaderEntity
	 */
	public PembelianHeader mapPembelianHeaderEntityToPembelianHeader(PembelianHeaderEntity pembelianHeaderEntity) {
		if(pembelianHeaderEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PembelianHeader pembelianHeader = map(pembelianHeaderEntity, PembelianHeader.class);

		return pembelianHeader;
	}
	
	/**
	 * Mapping from 'PembelianHeader' to 'PembelianHeaderEntity'
	 * @param pembelianHeader
	 * @param pembelianHeaderEntity
	 */
	public void mapPembelianHeaderToPembelianHeaderEntity(PembelianHeader pembelianHeader, PembelianHeaderEntity pembelianHeaderEntity) {
		if(pembelianHeader == null) {
			return;
		}

		//--- Generic mapping 
		map(pembelianHeader, pembelianHeaderEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}