/*
 * Created on 25 Jul 2021 ( Time 02:07:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.PenjualanHeader;
import org.demo.bean.jpa.PenjualanHeaderEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PenjualanHeaderServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PenjualanHeaderServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PenjualanHeaderEntity' to 'PenjualanHeader'
	 * @param penjualanHeaderEntity
	 */
	public PenjualanHeader mapPenjualanHeaderEntityToPenjualanHeader(PenjualanHeaderEntity penjualanHeaderEntity) {
		if(penjualanHeaderEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PenjualanHeader penjualanHeader = map(penjualanHeaderEntity, PenjualanHeader.class);

		return penjualanHeader;
	}
	
	/**
	 * Mapping from 'PenjualanHeader' to 'PenjualanHeaderEntity'
	 * @param penjualanHeader
	 * @param penjualanHeaderEntity
	 */
	public void mapPenjualanHeaderToPenjualanHeaderEntity(PenjualanHeader penjualanHeader, PenjualanHeaderEntity penjualanHeaderEntity) {
		if(penjualanHeader == null) {
			return;
		}

		//--- Generic mapping 
		map(penjualanHeader, penjualanHeaderEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}