/*
 * Created on 25 Jul 2021 ( Time 02:07:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.ReturPembelian;
import org.demo.bean.jpa.ReturPembelianEntity;
import org.demo.bean.jpa.PembelianHeaderEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ReturPembelianServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ReturPembelianServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ReturPembelianEntity' to 'ReturPembelian'
	 * @param returPembelianEntity
	 */
	public ReturPembelian mapReturPembelianEntityToReturPembelian(ReturPembelianEntity returPembelianEntity) {
		if(returPembelianEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ReturPembelian returPembelian = map(returPembelianEntity, ReturPembelian.class);

		//--- Link mapping ( link to PembelianHeader )
		if(returPembelianEntity.getPembelianHeader2() != null) {
			returPembelian.setPembelianHeader(returPembelianEntity.getPembelianHeader2().getIdPembelian());
		}
		return returPembelian;
	}
	
	/**
	 * Mapping from 'ReturPembelian' to 'ReturPembelianEntity'
	 * @param returPembelian
	 * @param returPembelianEntity
	 */
	public void mapReturPembelianToReturPembelianEntity(ReturPembelian returPembelian, ReturPembelianEntity returPembelianEntity) {
		if(returPembelian == null) {
			return;
		}

		//--- Generic mapping 
		map(returPembelian, returPembelianEntity);

		//--- Link mapping ( link : returPembelian )
		if( hasLinkToPembelianHeader(returPembelian) ) {
			PembelianHeaderEntity pembelianHeader1 = new PembelianHeaderEntity();
			pembelianHeader1.setIdPembelian( returPembelian.getPembelianHeader() );
			returPembelianEntity.setPembelianHeader2( pembelianHeader1 );
		} else {
			returPembelianEntity.setPembelianHeader2( null );
		}

	}
	
	/**
	 * Verify that PembelianHeader id is valid.
	 * @param PembelianHeader PembelianHeader
	 * @return boolean
	 */
	private boolean hasLinkToPembelianHeader(ReturPembelian returPembelian) {
		if(returPembelian.getPembelianHeader() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}