/*
 * Created on 25 Jul 2021 ( Time 02:07:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Barang;
import org.demo.bean.jpa.BarangEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class BarangServiceMapperTest {

	private BarangServiceMapper barangServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		barangServiceMapper = new BarangServiceMapper();
		barangServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'BarangEntity' to 'Barang'
	 * @param barangEntity
	 */
	@Test
	public void testMapBarangEntityToBarang() {
		// Given
		BarangEntity barangEntity = new BarangEntity();
		barangEntity.setNamaBarang(mockValues.nextString(100));
		barangEntity.setHarga(mockValues.nextDouble());
		
		// When
		Barang barang = barangServiceMapper.mapBarangEntityToBarang(barangEntity);
		
		// Then
		assertEquals(barangEntity.getNamaBarang(), barang.getNamaBarang());
		assertEquals(barangEntity.getHarga(), barang.getHarga());
	}
	
	/**
	 * Test : Mapping from 'Barang' to 'BarangEntity'
	 */
	@Test
	public void testMapBarangToBarangEntity() {
		// Given
		Barang barang = new Barang();
		barang.setNamaBarang(mockValues.nextString(100));
		barang.setHarga(mockValues.nextDouble());

		BarangEntity barangEntity = new BarangEntity();
		
		// When
		barangServiceMapper.mapBarangToBarangEntity(barang, barangEntity);
		
		// Then
		assertEquals(barang.getNamaBarang(), barangEntity.getNamaBarang());
		assertEquals(barang.getHarga(), barangEntity.getHarga());
	}

}