/*
 * Created on 25 Jul 2021 ( Time 02:07:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Login;
import org.demo.bean.jpa.LoginEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class LoginServiceMapperTest {

	private LoginServiceMapper loginServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		loginServiceMapper = new LoginServiceMapper();
		loginServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'LoginEntity' to 'Login'
	 * @param loginEntity
	 */
	@Test
	public void testMapLoginEntityToLogin() {
		// Given
		LoginEntity loginEntity = new LoginEntity();
		loginEntity.setPassword(mockValues.nextString(100));
		
		// When
		Login login = loginServiceMapper.mapLoginEntityToLogin(loginEntity);
		
		// Then
		assertEquals(loginEntity.getPassword(), login.getPassword());
	}
	
	/**
	 * Test : Mapping from 'Login' to 'LoginEntity'
	 */
	@Test
	public void testMapLoginToLoginEntity() {
		// Given
		Login login = new Login();
		login.setPassword(mockValues.nextString(100));

		LoginEntity loginEntity = new LoginEntity();
		
		// When
		loginServiceMapper.mapLoginToLoginEntity(login, loginEntity);
		
		// Then
		assertEquals(login.getPassword(), loginEntity.getPassword());
	}

}