/*
 * Created on 25 Jul 2021 ( Time 02:07:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.PembelianDetail;
import org.demo.bean.jpa.PembelianDetailEntity;
import org.demo.bean.jpa.PembelianHeaderEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PembelianDetailServiceMapperTest {

	private PembelianDetailServiceMapper pembelianDetailServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		pembelianDetailServiceMapper = new PembelianDetailServiceMapper();
		pembelianDetailServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PembelianDetailEntity' to 'PembelianDetail'
	 * @param pembelianDetailEntity
	 */
	@Test
	public void testMapPembelianDetailEntityToPembelianDetail() {
		// Given
		PembelianDetailEntity pembelianDetailEntity = new PembelianDetailEntity();
		pembelianDetailEntity.setHarga(mockValues.nextDouble());
		pembelianDetailEntity.setJumlah(mockValues.nextInteger());
		pembelianDetailEntity.setNamaBarang(mockValues.nextString(100));
		pembelianDetailEntity.setTotal(mockValues.nextDouble());
		pembelianDetailEntity.setPembelianHeader2(new PembelianHeaderEntity());
		pembelianDetailEntity.getPembelianHeader2().setIdPembelian(mockValues.nextInteger());
		
		// When
		PembelianDetail pembelianDetail = pembelianDetailServiceMapper.mapPembelianDetailEntityToPembelianDetail(pembelianDetailEntity);
		
		// Then
		assertEquals(pembelianDetailEntity.getHarga(), pembelianDetail.getHarga());
		assertEquals(pembelianDetailEntity.getJumlah(), pembelianDetail.getJumlah());
		assertEquals(pembelianDetailEntity.getNamaBarang(), pembelianDetail.getNamaBarang());
		assertEquals(pembelianDetailEntity.getTotal(), pembelianDetail.getTotal());
		assertEquals(pembelianDetailEntity.getPembelianHeader2().getIdPembelian(), pembelianDetail.getPembelianHeader());
	}
	
	/**
	 * Test : Mapping from 'PembelianDetail' to 'PembelianDetailEntity'
	 */
	@Test
	public void testMapPembelianDetailToPembelianDetailEntity() {
		// Given
		PembelianDetail pembelianDetail = new PembelianDetail();
		pembelianDetail.setHarga(mockValues.nextDouble());
		pembelianDetail.setJumlah(mockValues.nextInteger());
		pembelianDetail.setNamaBarang(mockValues.nextString(100));
		pembelianDetail.setTotal(mockValues.nextDouble());
		pembelianDetail.setPembelianHeader(mockValues.nextInteger());

		PembelianDetailEntity pembelianDetailEntity = new PembelianDetailEntity();
		
		// When
		pembelianDetailServiceMapper.mapPembelianDetailToPembelianDetailEntity(pembelianDetail, pembelianDetailEntity);
		
		// Then
		assertEquals(pembelianDetail.getHarga(), pembelianDetailEntity.getHarga());
		assertEquals(pembelianDetail.getJumlah(), pembelianDetailEntity.getJumlah());
		assertEquals(pembelianDetail.getNamaBarang(), pembelianDetailEntity.getNamaBarang());
		assertEquals(pembelianDetail.getTotal(), pembelianDetailEntity.getTotal());
		assertEquals(pembelianDetail.getPembelianHeader(), pembelianDetailEntity.getPembelianHeader2().getIdPembelian());
	}

}