/*
 * Created on 25 Jul 2021 ( Time 02:07:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.ReturPenjualan;
import org.demo.bean.jpa.ReturPenjualanEntity;
import org.demo.bean.jpa.PenjualanHeaderEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ReturPenjualanServiceMapperTest {

	private ReturPenjualanServiceMapper returPenjualanServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		returPenjualanServiceMapper = new ReturPenjualanServiceMapper();
		returPenjualanServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ReturPenjualanEntity' to 'ReturPenjualan'
	 * @param returPenjualanEntity
	 */
	@Test
	public void testMapReturPenjualanEntityToReturPenjualan() {
		// Given
		ReturPenjualanEntity returPenjualanEntity = new ReturPenjualanEntity();
		returPenjualanEntity.setHarga(mockValues.nextDouble());
		returPenjualanEntity.setJumlah(mockValues.nextInteger());
		returPenjualanEntity.setNamaBarang(mockValues.nextString(45));
		returPenjualanEntity.setTanggal(mockValues.nextDate());
		returPenjualanEntity.setTotal(mockValues.nextDouble());
		returPenjualanEntity.setPenjualanHeader2(new PenjualanHeaderEntity());
		returPenjualanEntity.getPenjualanHeader2().setIdPenjualanHeader(mockValues.nextInteger());
		
		// When
		ReturPenjualan returPenjualan = returPenjualanServiceMapper.mapReturPenjualanEntityToReturPenjualan(returPenjualanEntity);
		
		// Then
		assertEquals(returPenjualanEntity.getHarga(), returPenjualan.getHarga());
		assertEquals(returPenjualanEntity.getJumlah(), returPenjualan.getJumlah());
		assertEquals(returPenjualanEntity.getNamaBarang(), returPenjualan.getNamaBarang());
		assertEquals(returPenjualanEntity.getTanggal(), returPenjualan.getTanggal());
		assertEquals(returPenjualanEntity.getTotal(), returPenjualan.getTotal());
		assertEquals(returPenjualanEntity.getPenjualanHeader2().getIdPenjualanHeader(), returPenjualan.getPenjualanHeader());
	}
	
	/**
	 * Test : Mapping from 'ReturPenjualan' to 'ReturPenjualanEntity'
	 */
	@Test
	public void testMapReturPenjualanToReturPenjualanEntity() {
		// Given
		ReturPenjualan returPenjualan = new ReturPenjualan();
		returPenjualan.setHarga(mockValues.nextDouble());
		returPenjualan.setJumlah(mockValues.nextInteger());
		returPenjualan.setNamaBarang(mockValues.nextString(45));
		returPenjualan.setTanggal(mockValues.nextDate());
		returPenjualan.setTotal(mockValues.nextDouble());
		returPenjualan.setPenjualanHeader(mockValues.nextInteger());

		ReturPenjualanEntity returPenjualanEntity = new ReturPenjualanEntity();
		
		// When
		returPenjualanServiceMapper.mapReturPenjualanToReturPenjualanEntity(returPenjualan, returPenjualanEntity);
		
		// Then
		assertEquals(returPenjualan.getHarga(), returPenjualanEntity.getHarga());
		assertEquals(returPenjualan.getJumlah(), returPenjualanEntity.getJumlah());
		assertEquals(returPenjualan.getNamaBarang(), returPenjualanEntity.getNamaBarang());
		assertEquals(returPenjualan.getTanggal(), returPenjualanEntity.getTanggal());
		assertEquals(returPenjualan.getTotal(), returPenjualanEntity.getTotal());
		assertEquals(returPenjualan.getPenjualanHeader(), returPenjualanEntity.getPenjualanHeader2().getIdPenjualanHeader());
	}

}