/*
 * Created on 25 Jul 2021 ( Time 02:07:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.ReturPembelian;
import org.demo.bean.jpa.ReturPembelianEntity;
import org.demo.bean.jpa.PembelianHeaderEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ReturPembelianServiceMapperTest {

	private ReturPembelianServiceMapper returPembelianServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		returPembelianServiceMapper = new ReturPembelianServiceMapper();
		returPembelianServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ReturPembelianEntity' to 'ReturPembelian'
	 * @param returPembelianEntity
	 */
	@Test
	public void testMapReturPembelianEntityToReturPembelian() {
		// Given
		ReturPembelianEntity returPembelianEntity = new ReturPembelianEntity();
		returPembelianEntity.setHarga(mockValues.nextDouble());
		returPembelianEntity.setJumlah(mockValues.nextInteger());
		returPembelianEntity.setNamaBarang(mockValues.nextString(45));
		returPembelianEntity.setTanggal(mockValues.nextDate());
		returPembelianEntity.setTotal(mockValues.nextDouble());
		returPembelianEntity.setPembelianHeader2(new PembelianHeaderEntity());
		returPembelianEntity.getPembelianHeader2().setIdPembelian(mockValues.nextInteger());
		
		// When
		ReturPembelian returPembelian = returPembelianServiceMapper.mapReturPembelianEntityToReturPembelian(returPembelianEntity);
		
		// Then
		assertEquals(returPembelianEntity.getHarga(), returPembelian.getHarga());
		assertEquals(returPembelianEntity.getJumlah(), returPembelian.getJumlah());
		assertEquals(returPembelianEntity.getNamaBarang(), returPembelian.getNamaBarang());
		assertEquals(returPembelianEntity.getTanggal(), returPembelian.getTanggal());
		assertEquals(returPembelianEntity.getTotal(), returPembelian.getTotal());
		assertEquals(returPembelianEntity.getPembelianHeader2().getIdPembelian(), returPembelian.getPembelianHeader());
	}
	
	/**
	 * Test : Mapping from 'ReturPembelian' to 'ReturPembelianEntity'
	 */
	@Test
	public void testMapReturPembelianToReturPembelianEntity() {
		// Given
		ReturPembelian returPembelian = new ReturPembelian();
		returPembelian.setHarga(mockValues.nextDouble());
		returPembelian.setJumlah(mockValues.nextInteger());
		returPembelian.setNamaBarang(mockValues.nextString(45));
		returPembelian.setTanggal(mockValues.nextDate());
		returPembelian.setTotal(mockValues.nextDouble());
		returPembelian.setPembelianHeader(mockValues.nextInteger());

		ReturPembelianEntity returPembelianEntity = new ReturPembelianEntity();
		
		// When
		returPembelianServiceMapper.mapReturPembelianToReturPembelianEntity(returPembelian, returPembelianEntity);
		
		// Then
		assertEquals(returPembelian.getHarga(), returPembelianEntity.getHarga());
		assertEquals(returPembelian.getJumlah(), returPembelianEntity.getJumlah());
		assertEquals(returPembelian.getNamaBarang(), returPembelianEntity.getNamaBarang());
		assertEquals(returPembelian.getTanggal(), returPembelianEntity.getTanggal());
		assertEquals(returPembelian.getTotal(), returPembelianEntity.getTotal());
		assertEquals(returPembelian.getPembelianHeader(), returPembelianEntity.getPembelianHeader2().getIdPembelian());
	}

}