/*
 * Created on 25 Jul 2021 ( Time 02:07:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Barang implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 10 )
    private String kodeBarang;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String namaBarang;

    @NotNull
    private Double harga;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKodeBarang( String kodeBarang ) {
        this.kodeBarang = kodeBarang ;
    }

    public String getKodeBarang() {
        return this.kodeBarang;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNamaBarang( String namaBarang ) {
        this.namaBarang = namaBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }

    public void setHarga( Double harga ) {
        this.harga = harga;
    }
    public Double getHarga() {
        return this.harga;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(kodeBarang);
        sb.append("|");
        sb.append(namaBarang);
        sb.append("|");
        sb.append(harga);
        return sb.toString(); 
    } 


}
