/*
 * Created on 25 Jul 2021 ( Time 02:07:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Mekanik implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 15 )
    private String idMekanik;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 45 )
    private String namaMekanik;

    @NotNull
    @Size( min = 1, max = 13 )
    private String noHp;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMekanik( String idMekanik ) {
        this.idMekanik = idMekanik ;
    }

    public String getIdMekanik() {
        return this.idMekanik;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNamaMekanik( String namaMekanik ) {
        this.namaMekanik = namaMekanik;
    }
    public String getNamaMekanik() {
        return this.namaMekanik;
    }

    public void setNoHp( String noHp ) {
        this.noHp = noHp;
    }
    public String getNoHp() {
        return this.noHp;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idMekanik);
        sb.append("|");
        sb.append(namaMekanik);
        sb.append("|");
        sb.append(noHp);
        return sb.toString(); 
    } 


}
