/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class PembelianDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idPembelianDetail;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Double harga;

    @NotNull
    private Integer jumlah;

    @NotNull
    @Size( min = 1, max = 100 )
    private String namaBarang;

    @NotNull
    private Double total;


    private Integer pembelianHeader;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPembelianDetail( Integer idPembelianDetail ) {
        this.idPembelianDetail = idPembelianDetail ;
    }

    public Integer getIdPembelianDetail() {
        return this.idPembelianDetail;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setHarga( Double harga ) {
        this.harga = harga;
    }
    public Double getHarga() {
        return this.harga;
    }

    public void setJumlah( Integer jumlah ) {
        this.jumlah = jumlah;
    }
    public Integer getJumlah() {
        return this.jumlah;
    }

    public void setNamaBarang( String namaBarang ) {
        this.namaBarang = namaBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }

    public void setTotal( Double total ) {
        this.total = total;
    }
    public Double getTotal() {
        return this.total;
    }

    public void setPembelianHeader( Integer pembelianHeader ) {
        this.pembelianHeader = pembelianHeader;
    }
    public Integer getPembelianHeader() {
        return this.pembelianHeader;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idPembelianDetail);
        sb.append("|");
        sb.append(harga);
        sb.append("|");
        sb.append(jumlah);
        sb.append("|");
        sb.append(namaBarang);
        sb.append("|");
        sb.append(total);
        sb.append("|");
        sb.append(pembelianHeader);
        return sb.toString(); 
    } 


}
