/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class PembelianHeader implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idPembelian;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Date tanggal;

    @NotNull
    @Size( min = 1, max = 100 )
    private String supplier;

    @NotNull
    private Double total;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPembelian( Integer idPembelian ) {
        this.idPembelian = idPembelian ;
    }

    public Integer getIdPembelian() {
        return this.idPembelian;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTanggal( Date tanggal ) {
        this.tanggal = tanggal;
    }
    public Date getTanggal() {
        return this.tanggal;
    }

    public void setSupplier( String supplier ) {
        this.supplier = supplier;
    }
    public String getSupplier() {
        return this.supplier;
    }

    public void setTotal( Double total ) {
        this.total = total;
    }
    public Double getTotal() {
        return this.total;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idPembelian);
        sb.append("|");
        sb.append(tanggal);
        sb.append("|");
        sb.append(supplier);
        sb.append("|");
        sb.append(total);
        return sb.toString(); 
    } 


}
