/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;
import java.util.Date;

public class PenjualanHeader implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idPenjualanHeader;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Date tanggal;

    @NotNull
    private BigDecimal total;

    @Size( max = 45 )
    private String namaMekanik;


    private BigDecimal ongkosMekanik;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPenjualanHeader( Integer idPenjualanHeader ) {
        this.idPenjualanHeader = idPenjualanHeader ;
    }

    public Integer getIdPenjualanHeader() {
        return this.idPenjualanHeader;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTanggal( Date tanggal ) {
        this.tanggal = tanggal;
    }
    public Date getTanggal() {
        return this.tanggal;
    }

    public void setTotal( BigDecimal total ) {
        this.total = total;
    }
    public BigDecimal getTotal() {
        return this.total;
    }

    public void setNamaMekanik( String namaMekanik ) {
        this.namaMekanik = namaMekanik;
    }
    public String getNamaMekanik() {
        return this.namaMekanik;
    }

    public void setOngkosMekanik( BigDecimal ongkosMekanik ) {
        this.ongkosMekanik = ongkosMekanik;
    }
    public BigDecimal getOngkosMekanik() {
        return this.ongkosMekanik;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idPenjualanHeader);
        sb.append("|");
        sb.append(tanggal);
        sb.append("|");
        sb.append(total);
        sb.append("|");
        sb.append(namaMekanik);
        sb.append("|");
        sb.append(ongkosMekanik);
        return sb.toString(); 
    } 


}
