/*
 * Created on 25 Jul 2021 ( Time 02:07:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "pembelian_detail"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="pembelian_detail", catalog="bengkel_nirwana" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PembelianDetailEntity.countAll", query="SELECT COUNT(x) FROM PembelianDetailEntity x" )
} )
public class PembelianDetailEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_pembelian_detail", nullable=false)
    private Integer    idPembelianDetail ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="harga", nullable=false)
    private Double     harga        ;

    @Column(name="jumlah", nullable=false)
    private Integer    jumlah       ;

    @Column(name="nama_barang", nullable=false, length=100)
    private String     namaBarang   ;

    @Column(name="total", nullable=false)
    private Double     total        ;

	// "pembelianHeader" (column "pembelian_header") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="pembelian_header", referencedColumnName="id_pembelian")
    private PembelianHeaderEntity pembelianHeader2;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PembelianDetailEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPembelianDetail( Integer idPembelianDetail ) {
        this.idPembelianDetail = idPembelianDetail ;
    }
    public Integer getIdPembelianDetail() {
        return this.idPembelianDetail;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : harga ( DOUBLE ) 
    public void setHarga( Double harga ) {
        this.harga = harga;
    }
    public Double getHarga() {
        return this.harga;
    }

    //--- DATABASE MAPPING : jumlah ( INT ) 
    public void setJumlah( Integer jumlah ) {
        this.jumlah = jumlah;
    }
    public Integer getJumlah() {
        return this.jumlah;
    }

    //--- DATABASE MAPPING : nama_barang ( VARCHAR ) 
    public void setNamaBarang( String namaBarang ) {
        this.namaBarang = namaBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }

    //--- DATABASE MAPPING : total ( DOUBLE ) 
    public void setTotal( Double total ) {
        this.total = total;
    }
    public Double getTotal() {
        return this.total;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPembelianHeader2( PembelianHeaderEntity pembelianHeader2 ) {
        this.pembelianHeader2 = pembelianHeader2;
    }
    public PembelianHeaderEntity getPembelianHeader2() {
        return this.pembelianHeader2;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idPembelianDetail);
        sb.append("]:"); 
        sb.append(harga);
        sb.append("|");
        sb.append(jumlah);
        sb.append("|");
        sb.append(namaBarang);
        sb.append("|");
        sb.append(total);
        return sb.toString(); 
    } 

}
