/*
 * Created on 25 Jul 2021 ( Time 02:07:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.common;

public enum MessageType {
	
	SUCCESS,
	INFO,
	WARNING,
	DANGER;
	
	public String getCss() {
		return name().toLowerCase();
	}
	
}
