/*
 * Created on 25 Jul 2021 ( Time 02:07:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Login;

/**
 * Business Service Interface for entity Login.
 */
public interface LoginService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param userName
	 * @return entity
	 */
	Login findById( String userName  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Login> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Login save(Login entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Login update(Login entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Login create(Login entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param userName
	 */
	void delete( String userName );


}
