/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Mekanik;

/**
 * Business Service Interface for entity Mekanik.
 */
public interface MekanikService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idMekanik
	 * @return entity
	 */
	Mekanik findById( String idMekanik  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Mekanik> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Mekanik save(Mekanik entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Mekanik update(Mekanik entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Mekanik create(Mekanik entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idMekanik
	 */
	void delete( String idMekanik );


}
