/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.PembelianDetail;

/**
 * Business Service Interface for entity PembelianDetail.
 */
public interface PembelianDetailService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idPembelianDetail
	 * @return entity
	 */
	PembelianDetail findById( Integer idPembelianDetail  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PembelianDetail> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PembelianDetail save(PembelianDetail entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PembelianDetail update(PembelianDetail entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PembelianDetail create(PembelianDetail entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idPembelianDetail
	 */
	void delete( Integer idPembelianDetail );


}
