/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.PembelianHeader;

/**
 * Business Service Interface for entity PembelianHeader.
 */
public interface PembelianHeaderService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idPembelian
	 * @return entity
	 */
	PembelianHeader findById( Integer idPembelian  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PembelianHeader> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PembelianHeader save(PembelianHeader entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PembelianHeader update(PembelianHeader entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PembelianHeader create(PembelianHeader entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idPembelian
	 */
	void delete( Integer idPembelian );


}
