/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.PenjualanHeader;

/**
 * Business Service Interface for entity PenjualanHeader.
 */
public interface PenjualanHeaderService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idPenjualanHeader
	 * @return entity
	 */
	PenjualanHeader findById( Integer idPenjualanHeader  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PenjualanHeader> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PenjualanHeader save(PenjualanHeader entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PenjualanHeader update(PenjualanHeader entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PenjualanHeader create(PenjualanHeader entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idPenjualanHeader
	 */
	void delete( Integer idPenjualanHeader );


}
