/*
 * Created on 25 Jul 2021 ( Time 02:07:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.ReturPenjualan;

/**
 * Business Service Interface for entity ReturPenjualan.
 */
public interface ReturPenjualanService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idreturPenjualan
	 * @return entity
	 */
	ReturPenjualan findById( Integer idreturPenjualan  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ReturPenjualan> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ReturPenjualan save(ReturPenjualan entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReturPenjualan update(ReturPenjualan entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReturPenjualan create(ReturPenjualan entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idreturPenjualan
	 */
	void delete( Integer idreturPenjualan );


}
