/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.ReturPembelian;

/**
 * Business Service Interface for entity ReturPembelian.
 */
public interface ReturPembelianService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idreturPembelian
	 * @return entity
	 */
	ReturPembelian findById( Integer idreturPembelian  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ReturPembelian> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ReturPembelian save(ReturPembelian entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReturPembelian update(ReturPembelian entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReturPembelian create(ReturPembelian entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idreturPembelian
	 */
	void delete( Integer idreturPembelian );


}
