/*
 * Created on 25 Jul 2021 ( Time 02:07:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.Barang;
import org.demo.web.common.ListItem;

public class BarangListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BarangListItem(Barang barang) {
		super();

		this.value = ""
			 + barang.getKodeBarang()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = barang.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
