/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.PenjualanHeader;
import org.demo.web.common.ListItem;

public class PenjualanHeaderListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PenjualanHeaderListItem(PenjualanHeader penjualanHeader) {
		super();

		this.value = ""
			 + penjualanHeader.getIdPenjualanHeader()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = penjualanHeader.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
