/*
 * Created on 25 Jul 2021 ( Time 02:07:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.ReturPenjualan;
import org.demo.business.service.ReturPenjualanService;
import org.demo.web.listitem.ReturPenjualanListItem;

/**
 * Spring MVC controller for 'ReturPenjualan' management.
 */
@Controller
public class ReturPenjualanRestController {

	@Resource
	private ReturPenjualanService returPenjualanService;
	
	@RequestMapping( value="/items/returPenjualan",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ReturPenjualanListItem> findAllAsListItems() {
		List<ReturPenjualan> list = returPenjualanService.findAll();
		List<ReturPenjualanListItem> items = new LinkedList<ReturPenjualanListItem>();
		for ( ReturPenjualan returPenjualan : list ) {
			items.add(new ReturPenjualanListItem( returPenjualan ) );
		}
		return items;
	}
	
	@RequestMapping( value="/returPenjualan",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ReturPenjualan> findAll() {
		return returPenjualanService.findAll();
	}

	@RequestMapping( value="/returPenjualan/{idreturPenjualan}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturPenjualan findOne(@PathVariable("idreturPenjualan") Integer idreturPenjualan) {
		return returPenjualanService.findById(idreturPenjualan);
	}
	
	@RequestMapping( value="/returPenjualan",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturPenjualan create(@RequestBody ReturPenjualan returPenjualan) {
		return returPenjualanService.create(returPenjualan);
	}

	@RequestMapping( value="/returPenjualan/{idreturPenjualan}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturPenjualan update(@PathVariable("idreturPenjualan") Integer idreturPenjualan, @RequestBody ReturPenjualan returPenjualan) {
		return returPenjualanService.update(returPenjualan);
	}

	@RequestMapping( value="/returPenjualan/{idreturPenjualan}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("idreturPenjualan") Integer idreturPenjualan) {
		returPenjualanService.delete(idreturPenjualan);
	}
	
}
