/*
 * Created on 25 Jul 2021 ( Time 02:07:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.ReturPembelian;
import org.demo.business.service.ReturPembelianService;
import org.demo.web.listitem.ReturPembelianListItem;

/**
 * Spring MVC controller for 'ReturPembelian' management.
 */
@Controller
public class ReturPembelianRestController {

	@Resource
	private ReturPembelianService returPembelianService;
	
	@RequestMapping( value="/items/returPembelian",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ReturPembelianListItem> findAllAsListItems() {
		List<ReturPembelian> list = returPembelianService.findAll();
		List<ReturPembelianListItem> items = new LinkedList<ReturPembelianListItem>();
		for ( ReturPembelian returPembelian : list ) {
			items.add(new ReturPembelianListItem( returPembelian ) );
		}
		return items;
	}
	
	@RequestMapping( value="/returPembelian",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ReturPembelian> findAll() {
		return returPembelianService.findAll();
	}

	@RequestMapping( value="/returPembelian/{idreturPembelian}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturPembelian findOne(@PathVariable("idreturPembelian") Integer idreturPembelian) {
		return returPembelianService.findById(idreturPembelian);
	}
	
	@RequestMapping( value="/returPembelian",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturPembelian create(@RequestBody ReturPembelian returPembelian) {
		return returPembelianService.create(returPembelian);
	}

	@RequestMapping( value="/returPembelian/{idreturPembelian}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturPembelian update(@PathVariable("idreturPembelian") Integer idreturPembelian, @RequestBody ReturPembelian returPembelian) {
		return returPembelianService.update(returPembelian);
	}

	@RequestMapping( value="/returPembelian/{idreturPembelian}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("idreturPembelian") Integer idreturPembelian) {
		returPembelianService.delete(idreturPembelian);
	}
	
}
